### (1)外部REQUIRED 内部REQUIRES_NEW
### 外部catch内部异常：外部提交。 内部抛异常：内部回滚
GET http://localhost:8080/user/OUT_REQUIRED_IN_REQUIRES_NEW_EXCE

### 外部抛异常：外部回滚。 内部正常提交
GET http://localhost:8080/user/OUT_REQUIRED_EXEC_IN_REQUIRES_NEW


### (2)外部REQUIRED 内部NESTED
### 外部catch内部异常：外部提交。 内部抛异常：内部回滚
GET http://localhost:8080/user/OUT_REQUIRED_IN_NESTED_EXCE

### 外部异常：外部回滚。 内部无异常：内部回滚 （事务同进退）
GET http://localhost:8080/user/OUT_REQUIRED_EXEC_IN_NESTED


### (3)外部REQUIRED 内部REQUIRED
### 外部catch内部异常：外部回滚。 内部抛异常：内部回滚
GET http://localhost:8080/user/OUT_REQUIRED_IN_REQUIRED_EXCE

### 外部异常：外部回滚。 内部无异常：内部回滚
GET http://localhost:8080/user/OUT_REQUIRED_EXEC_IN_REQUIRED


### (4)外部REQUIRED 内部NOT_SUPPORTED 内内部REQUIRED
### 外部事务提交 内部事务提交 内内部事务回滚
GET http://localhost:8080/user/OUT_REQUIRED_IN_NOT_SUPPORTED_ININ_REQUIRED

### 外部事务抛异常 回滚  内部事务提交 内内部事务 提交
GET http://localhost:8080/user/OUT_REQUIRED_EXEC_IN_NOT_SUPPORTED_ININ_REQUIRED


###
GET http://localhost:8080/event/publishEvent